### ISSUE TITLE
Can you please have a look in my method?

### ISSUE THREAD

**Issue by DusKing1** [atomgomba/orangebox#5]
I'm trying to use orangebox to get rid of .exe files to make my own blackbox tool become not that platform needed.

The target format of data is having each variation in a 1-d array, so I can easily operate them with numpy.

But it seems my code is not performed that well. Can you take a look?

https://github.com/DusKing1/PID-Evaluator/blob/master/orangebox-approach.ipynb

**Comment by atomgomba** [comment]
Closing this as stale
