### ISSUE TITLE
iNAV log error - No predictor found for 10

### ISSUE THREAD

**Issue by Matthias84** [atomgomba/orangebox#6]
Hi, I appreciate your lib and like to use it to load it for plots, qgis or kdenlive visualisation.
Unfortunatly the blackbox logs created by INAV 3 are .TXT files which cause the error message

> ~/.virtualenvs/orangebox/lib/python3.8/site-packages/orangebox/reader.py in _build_field_defs(self)
>    211                     if prop == "predictor":
>    212                         if framedef_value not in predictors:
>--> 213                             raise RuntimeError("No predictor found for {:d}".format(framedef_value))
>    214                         else:
>    215                             field_defs[frame_type][i].predictorfun = predictors[framedef_value]
>
>RuntimeError: No predictor found for 10

To my understanding, as another fork of cleanflight, the blackbox structures should be compatible?
The rendering using the official blackbox-viewer by betaflight works fine so far.

**Comment by atomgomba** [comment]
I don't know about iNav, but Betaflight logs are compressed binary data, definitely not plain text. Also please note that reading GPS data is not supported by this library at the moment. If you just want an output which is more straightforward to process, you can try the CSV Export function in Blackbox Log Viewer.

**Comment by Matthias84** [comment]
Hi, well yes beside of the extension, it's sort of structured information but I don't see any compression as BZIP for example.

My problem is, that blackbox viewer and blackbox utils work only on windows for me and I like to setup a blackbox workflow for linux and esp. python to debug my 1st custom drone.

Yes Predictor 10 seems to be relevant to GPS and event based value updates: https://github.com/iNavFlight/inav/blob/master/docs/development/Blackbox%20Internals.md
There is your GPS branch, does this already focus on this feature?

**Comment by atomgomba** [comment]
Support for GPS data is in development, closing this
