### ISSUE TITLE
tag8_8svb decoder fails when there are 8 fields

### ISSUE THREAD

**Issue by tblaha** [atomgomba/orangebox#7]
Thanks for this amazing project!

I came across this bug when actually using exactly 8 group for the TAG8_8SVB encoding. This occurs in a betaflight fork (github.com/tblaha/indiflight).
If exactly 8 fields are found in a TAG8_8SVB encoding group (the maximum), then group_count to 0, if 8 groups are found. This gets the parser get stuck in an endless loop, because `next(data)` is never called.
https://github.com/atomgomba/orangebox/blob/ef39128c5d7b4b5a8dddc2d3dbd10f45b18ab0e9/orangebox/decoders.py#L54-L75

Setting `group_count = 8` in line 57 seems to fix the issue in my logfiles.

AFAIK blackbox-log-viewer also has a similar bugs, will also raise an issue there.

---

Sidenote: TAG8_8SVB itself is already broken by definition if you use less than 8 fields and the next field is also encoded with TAG8_8SVB. If I have a TAG8_8SVB group with less than 8 values, followed by another TAG8_8SVB group, there is no way to know where the boundary is, as the number of values is not written in the logs. We only know which ones are zero or not, so if the first TAG8_8SVB has 4 values, then the last 4 are declared 0 in its header. The parser simply checks up to 8 fields for TAG8_8SVB encoding (and in this case will then also accept up to 4 fields from the next TAG8_8SVB group, which are then zero'd even though they may not be).

**Comment by atomgomba** [comment]
@tblaha Thank you for discovering this issue! While testing these decoders I have used the Blackbox Viewer as a reference implementation, so it won't be completely surprising if a similar issue had surfaced there as well. I think the reason this wasn't a problem in the past is that such a sequence of fields doesn't occur in original Betaflight.
